spring.application.name=App-Supermercado
#conexion mysql
spring.datasource.url=jdbc:mysql://localhost:3306/supermercado_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=tizona88
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configurar el patr€n del log (en lugar de logback-spring.xml)
logging.pattern.console=[%thread] %-5level: %logger - %msg%n
# Configurar el nivel de log (INFO en este caso)
logging.level.root=INFO
#Opcional, configurar niveles por paquetes
#logging.level.com.miapp=DEBUG
#logging.level.org.springframework=WARN
server.port:8086
spring.main.banner-mode=off
