spring.application.name=App-Supermercado

# --- CONEXIÓN A BASE DE DATOS (POSTGRESQL) ---
# En Render usaremos la variable DB_URL que nos dará la base de datos.
# Si no existe (en tu PC), buscará un Postgres local en el puerto 5432.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/supermercado_db}

# Credenciales dinámicas
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:88tizona}

# IMPORTANTE: Cambiamos el driver de MySQL a PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate para Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- CONFIGURACIÓN DE LOGS ---
logging.pattern.console=[%thread] %-5level: %logger - %msg%n
logging.level.root=INFO

# --- SERVIDOR ---
# Render asignará el puerto automáticamente. En local usará el 8086.
server.port=${PORT:8086}
spring.main.banner-mode=off