spring.application.name=App-Supermercado
#conexion mysql
# --- CONEXI”N A BASE DE DATOS ---
# Si existe DB_URL la usa, si no, usa tu localhost de MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/supermercado_db?createDatabaseIfNotExist=true}

# Si existe DB_USER lo usa, si no, usa root
spring.datasource.username=${DB_USER:root}

# Si existe DB_PASSWORD lo usa, si no, usa tu clave tizona88
spring.datasource.password=${DB_PASSWORD:tizona88}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configurar el patr€n del log (en lugar de logback-spring.xml)
logging.pattern.console=[%thread] %-5level: %logger - %msg%n
# Configurar el nivel de log (INFO en este caso)
logging.level.root=INFO
#Opcional, configurar niveles por paquetes
#logging.level.com.miapp=DEBUG
#logging.level.org.springframework=WARN
server.port=${PORT:8086}
spring.main.banner-mode=off
